/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const on_Customer_Replicate = require('./code/on-customer-replicate');

class oBMSSrv extends LCAPApplicationService {
    async init() {

        this.on('replicate', 'Customer', async (request) => {
            return on_Customer_Replicate(request);
        });

        return super.init();
    }
}


module.exports = {
    oBMSSrv
};